name: API Concatos CI/CD
on:
  push:
    branches: ["main"]

env:
  IMAGE_BASE_NAME: jhforero77/apicontactos

jobs:
  API_IMAGE:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Looking for files
        run: ls -a src/ContactosAPI

      - name: Build Docker Net Image
        run: docker build --platform linux -t $IMAGE_BASE_NAME -f src/ContactosAPI/DockerFile src/ContactosAPI/.
